# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm 

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 60
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 2
    gpus_per_node: 0
    mem_gb: 10
    # mem_per_cpu: 5
    name: ${hydra.job.name}
    # use environment of scheduler if present
    # cannot use interpolation in sweep https://github.com/facebookresearch/hydra/issues/1786
    setup: [
      # 'source ${path_modules}/modules.sh',
      'source /data/gent/vo/000/gvo00070/vsc43257/hydra_hpc_example/src/${name}/modules.sh',
      'source ${path_venv}/bin/activate',
      'which python'
    ]
    # we need to use the python from PATH, as the default is the submitting interpreter from sys.executable
    # can also be used to run from a container like Singularity/Apptainer...
    python: python


